# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180113_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 13, 8, 36, 43, 436429, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 13, 8, 36, 43, 434429, tzinfo=utc)),
        ),
    ]
